---
- name: Base security settings
  hosts: network
  roles:
    - common_security
  tags:
    - common
    - security

- name: Vlans
  hosts: switches
  roles:
    - vlans
  tags:
    - switching
    - vlans

- name: LAGG
  hosts:
    - distribution_switches
  roles:
    - link_aggregation
  tags:
    - switching
    - backbone
    - laggs

- name: Trunks
  hosts: switches
  roles:
    - vlan_trunks
  tags:
    - switching
    - trunks

- name: Spanning tree
  hosts: switches
  roles:
    - spanning_tree
  tags:
    - switching
    - spanning-tree

- name: OSPF routing
  hosts:
    - routers
    - distribution_switches
  roles:
    - ospf_router
  tags:
    - routing
    - backbone
    - ospf