servers:
  hosts:
    pc4:
      ansible_host: 10.0.20.13
network:
  children:
    routers:
      hosts:
        r1:
          ansible_host: 10.0.100.11
        r2:
          ansible_host: 10.0.100.12
    
    distribution_switches:
      hosts:
        sw-core-1:
          ansible_host: 10.0.90.251
        sw-core-2:
          ansible_host: 10.0.90.252

    access_switches:
      hosts:
        sw-acc-1:
          ansible_host: 10.0.90.11
        sw-acc-2:
          ansible_host: 10.0.90.12
        sw-acc-3:
          ansible_host: 10.0.90.13
        sw-acc-4:
          ansible_host: 10.0.90.14

    switches:
      children:
        distribution_switches:
        access_switches: