---
- name: "Create vlans"
  ios_vlans:
    config:
    - name: "{{ vlan_prefix }}{{ vlan['name'] }}"
      vlan_id: "{{ vlan['id'] }}"
  loop: "{{ vlans }}"
  loop_control:
    label: "{{ vlan['name'] }}"
    loop_var: vlan