---
ospf_process_id: 1
router_id: 1.1.1.1
reference_bandwidth: 100000
passive_interface_default: true
ospf_interfaces:
  - GigabitEthernet0/1

default_information_originate: false

ospf_networks:
  - address: 10.0.0.0
    wildcard_bits : 0.0.0.255
    area: 0