---
- name: Set OSPF configuration
  ios_ospfv2:
    config:
      processes:
      - process_id: "{{ospf_process_id}}"
        network: "{{ospf_networks}}"
        # default_information:  # bugged, always returns true
        #   originate: "{{default_information_originate}}"
        passive_interfaces:
          default: "{{passive_interface_default}}"
          interface:
            set_interface: false
            name: "{{ospf_interfaces}}"
    state: merged
