---
ansible_connection: network_cli
ansible_network_os: ios
ansible_become: yes
ansible_become_method: enable

# OSPF
reference_bandwidth: 1000000
passive_interface_default: true

ospf_networks:
  - address: 10.0.0.0
    wildcard_bits: 0.0.255.255
    area: 0
  - address: 172.16.0.0
    wildcard_bits: 0.0.0.255
    area: 0